[versions]
smithy = "1.38.0"

[libraries]

[libraries.smithy-model]
group = "software.amazon.smithy"
name = "smithy-model"
version.ref = "smithy"

[libraries.smithy-linters]
group = "software.amazon.smithy"
name = "smithy-linters"
version.ref = "smithy"

[libraries.smithy-aws-traits]
group = "software.amazon.smithy"
name = "smithy-aws-traits"
version.ref = "smithy"

[plugins]
smithy = { id = "software.amazon.smithy", version = "0.7.0" }
