[versions]
smithy = "1.25.1"

[libraries]

[libraries.smithy-model]
group = "software.amazon.smithy"
name = "smithy-model"
version.ref = "smithy"

[libraries.smithy-aws-traits]
group = "software.amazon.smithy"
name = "smithy-aws-traits"
version.ref = "smithy"

[plugins]
smithy = { id = "software.amazon.smithy", version = "0.6.0" }
