[versions]
smithy = "1.9.0"

[libraries]

[libraries.smithy-model]
group = "software.amazon.smithy"
name= "smithy-model"
version.ref = "smithy"

[libraries.smithy-aws-traits]
group = "software.amazon.smithy"
name= "smithy-aws-traits"
version.ref = "smithy"
