name: validate apiblueprint files

on: [push]

jobs:
  validate:
    runs-on: ubuntu-latest
    container: apiaryio/drafter
    steps:
      - uses: actions/checkout@v1
      - name: validate lake.md
        run: |
          ! drafter --validate apiary.apib 2>&1 | egrep -i "(warning|error)"
      - name: send failure alert
        if: ${{ failure() }}
        uses: appleboy/telegram-action@master
        with:
          format: markdown
          to: ${{ secrets.CI_FAILURE_TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_CI_TOKEN_RAW }}
          args: ${{ github.action }} failed in $repo failed after [commit](https://github.com/woog-life/$repo/$commit.sha) push
