name: Main
on:
  push:
    branches: [ main ]
  pull_request: { }

jobs:
  check:
    runs-on: ubuntu-latest
    container: eclipse-temurin:17
    steps:
      - uses: actions/checkout@v3
      - run: ./gradlew check
