name: Main
on:
  push:
    branches: [ main ]
  pull_request: { }

jobs:
  check:
    runs-on: ubuntu-latest
    container: eclipse-temurin:21
    steps:
      - uses: actions/checkout@v4
      - run: ./gradlew check
